version: '3.3'

services:
  nginx:
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/tbp.marktai.com/:/etc/certs/tbp.marktai.com
      - /etc/letsencrypt/archive/tbp.seas.ucla.edu/:/etc/certs/tbp.seas.ucla.edu
      - ./../edss_frontend/:/edss_frontend
