version: '3.3'

services:
  db:
    image: mysql:5.5.59 
    environment:
      - MYSQL_ROOT_PASSWORD=CAEpsilon
  backend:
    image: tbpsite/backend:latest
    build: backend 
    volumes:
      - ./backend:/app
      - tbpsite-static:/app/static
      - ./media:/media
      - ./update_virtual_domains.py:/etc/postfix_conf/update_virtual_domains.py
      - ./virtual_static:/etc/postfix_conf/virtual_static
      - ./postfix_conf:/etc/postfix_conf
    depends_on:
      - db
      
  nginx:
    image: tbpsite/nginx:latest
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - tbpsite-static:/static
      - ./media:/media
      - /etc/letsencrypt/archive/tbp.marktai.com/:/etc/certs
    depends_on:
      - backend

volumes:
  tbpsite-static:

