version: '3.3'

services:
  db:
    image: mysql:5.5.59 
    environment:
      - MYSQL_ROOT_PASSWORD=CAEpsilon
    volumes:
      - tbpsite-data:/var/lib/mysql
      
  backend:
    image: tbpsite/backend:latest
    build: backend 
    volumes:
      - ./backend:/app
      - tbpsite-static:/app/static
      - ./media:/media
    depends_on:
      - db
      
  nginx:
    image: tbpsite/nginx:latest
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - tbpsite-static:/static
      - ./media:/media
      - /etc/letsencrypt/archive/tbp.marktai.com/:/etc/certs/tbp.marktai.com
      - /etc/letsencrypt/archive/tbp.seas.ucla.edu/:/etc/certs/tbp.seas.ucla.edu
    depends_on:
      - backend

volumes:
  tbpsite-static:
  tbpsite-data:

